### ISSUE TITLE
希望新增一个查询当前访问者的出口IP

### ISSUE THREAD

**Issue by sifanx** [moys3389/ip2region-api#1]
你好，你提供的这个docker部署方式非常方便，在使用中发现，这个接口地址/api/search显示的是服务器的本地IP，希望能新增一个显示访问者出口IP的接口，比如路径什么都不输入，默认根路径 http://IP 访问就是显示访问者出口IP
![001](https://github.com/user-attachments/assets/023d1964-90f1-4c1d-90eb-c34ac66071de)

**Comment by moys3389** [comment]
你在公网环境部署，访问/api/search就会显示访问者的出口IP.

**Comment by sifanx** [comment]
好的，明白了。但是因为直接部署在公网，安全性很差，所以我是部署在外网局域网环境，通过外网局域网WAF防火墙代理，然后将WAF的443端口映射到公网上，进行域名绑定。现在是我不管在哪个地方通过互联网访问 https://域名/api/search，
都显示的是WAF防火墙本身的局域网IP：192.168.103.141，代码上能如何优化，显示访问者的IP吗？

**Comment by sifanx** [comment]
我询问了GPT，说是这样改的

![001](https://github.com/user-attachments/assets/0869c678-6b90-4c2d-8813-80a015d66684)

我看WAF防火墙有这么一个设置，为上游服务器传递 X-Forwarded-Host、 X-Forwarded-Proto，GPT写的是 X-Forwarded-For，不确定代码里需要取 X-Forwarded-Host 还是 X-Forwarded-For

![002](https://github.com/user-attachments/assets/23f18972-8122-49ea-8b93-845cf972c7d7)

**Comment by moys3389** [comment]
已经改了，更新下docker镜像试试。

**Comment by sifanx** [comment]
docker 0.0.4版本，已显示正常，谢谢更新~

![004](https://github.com/user-attachments/assets/74aff6ab-daa1-4ede-8432-560b703a8eb1)
