### ISSUE TITLE
希望新增一个查询结果显示页面，而非API接口

### ISSUE THREAD

**Issue by sifanx** [moys3389/ip2region-api#2]
希望新增一个查询结果显示页面，而非API接口，比如随便查询一个IP地址117.25.38.220，显示出的内容为“当前 IP：117.25.38.220  来自于：中国 福建省 福州市 电信”，而非JSON格式输出。
![003](https://github.com/user-attachments/assets/5e9fce02-4e5f-41ca-91f7-22939a66cd13)

**Comment by moys3389** [comment]
新版本增加了新路由地址，/api/search-page，返回结果显示页面。

**Comment by sifanx** [comment]
谢谢提供更新，更新docker后看到效果了~
