### ISSUE TITLE
docker如何更新ip2region.xdb文件？

### ISSUE THREAD

**Issue by sifanx** [moys3389/ip2region-api#3]
docker如何更新ip2region.xdb文件？路径在哪里？

**Comment by sifanx** [comment]
我发现有些IP的归属地不正确，我通过更新ip.merge.txt里的内容，用xdb_maker.exe重新生成ip2region.xdb，想替换到docker里，但是我没找到ip2region.xdb在哪里，新版本能否通过 docker -v 参数将IP数据文件映射到本地？

**Comment by sifanx** [comment]
我询问了GPT，你看看这样改可以吗？
![001](https://github.com/user-attachments/assets/70fce7d1-7a44-47be-8ce1-7a5b960dea6f)

**Comment by sifanx** [comment]
我看WAF防火墙有这么一个设置，为上游服务器传递 X-Forwarded-Host、 X-Forwarded-Proto，GPT写的是 X-Forwarded-For，不确定代码里需要取 X-Forwarded-Host 还是 X-Forwarded-For

![002](https://github.com/user-attachments/assets/30e48f8d-0ab7-434e-96c6-76a529d2204b)

**Comment by moys3389** [comment]
新版本已经增加了自定义xdb文件的支持.

**Comment by sifanx** [comment]
> 新版本已经增加了自定义xdb文件的支持.

docker 0.0.4 版本，使用这个命令运行后网页无法打开
docker run -d --name ip2region -p 8080:8080 -v /path/to/ip2region.xdb:/data/ip2region.xdb moys3389/ip2region-api:latest

进入docker镜像查看，可能是无这个路径映射失败导致 /data/ip2region.xdb

![003](https://github.com/user-attachments/assets/d42faefd-9dc2-4929-96f4-3403e94e6f6d)

**Comment by moys3389** [comment]
/path/to/ip2region.xdb 填你自己本机xdb文件目录地址

**Comment by sifanx** [comment]
> /path/to/ip2region.xdb 填你自己本机xdb文件目录地址

可以了，谢谢，是我自己的问题，需要提前把ip2region.xdb拷入本地目录，否则docker run命令会生成一个ip2region.xdb同名的文件夹的，导致程序异常。
