### ISSUE TITLE
访问首页显示“404 page not found”

### ISSUE THREAD

**Issue by sifanx** [moys3389/ip2region-api#4]
在不输入任何路径，只输入域名时，页面内容显示“404 page not found”，不是很人性化，建议访问首页，直接显示文本内容，而不是通过访问/api/search-page才能显示。

![005](https://github.com/user-attachments/assets/ec0f383f-a2c8-4cd8-a49a-b2a9a7fbab22)

建议改成如下访问方式

![006](https://github.com/user-attachments/assets/370a65aa-ed9a-418c-950b-ad5b0a4403ef)

**Comment by moys3389** [comment]
已经更新上去了。
